# Generated by Django 5.2.6 on 2026-03-31 16:57

import uuid

from django.db import migrations, models


def seed_default_ai_config(apps, schema_editor) -> None:
    """Ensure one default AI configuration exists."""
    AIConfiguration = apps.get_model("ai_config", "AIConfiguration")
    if AIConfiguration.objects.filter(is_default=True).exists():
        return
    AIConfiguration.objects.create(
        name="Default",
        system_prompt=(
            "Eres un asistente comercial del equipo Seeds ERP / Valfora. "
            "Responde en español, de forma breve, profesional y útil."
        ),
        is_default=True,
        temperature=0.7,
        max_tokens=512,
        llm_model="gpt-4o-mini",
        max_history_messages=20,
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(default="Default", max_length=120)),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True,
                        help_text="Instrucciones base para el asistente (idioma, tono, límites).",
                    ),
                ),
                ("temperature", models.FloatField(default=0.7)),
                ("max_tokens", models.PositiveIntegerField(default=512)),
                ("llm_model", models.CharField(default="gpt-4o-mini", max_length=80)),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                (
                    "max_history_messages",
                    models.PositiveSmallIntegerField(
                        default=20,
                        help_text="Mensajes de historial incluidos en el prompt.",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI configuration",
                "verbose_name_plural": "AI configurations",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.RunPython(seed_default_ai_config, migrations.RunPython.noop),
    ]
