# Generated by Django 5.2.6 on 2026-03-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_config", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiconfiguration",
            name="daily_token_budget_per_conversation",
            field=models.PositiveIntegerField(
                default=100000,
                help_text="Máximo de tokens (prompt+completion) por conversación y día UTC.",
            ),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="moderation_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Si está activo, las respuestas pasan por la API de moderación de OpenAI.",
            ),
        ),
    ]
