# Generated by Django 5.2.6 on 2026-03-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_config", "0002_bc_safety_handoff"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiconfiguration",
            name="rag_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Incluir fragmentos relevantes de documentos CRM (RAG) en el prompt.",
            ),
        ),
        migrations.AddField(
            model_name="aiconfiguration",
            name="rag_top_k",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="Número máximo de chunks de documentos a inyectar en el system prompt.",
            ),
        ),
    ]
