# Generated by Django 5.2.6 on 2026-05-11

import apps.ai_config.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_config", "0005_aiconfiguration_profile_fields_and_global_ai_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="airuntimesettings",
            name="google_booking_window_days",
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name="airuntimesettings",
            name="google_calendar_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="airuntimesettings",
            name="google_calendar_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="airuntimesettings",
            name="google_calendar_timezone",
            field=models.CharField(default="America/Bogota", max_length=64),
        ),
        migrations.AddField(
            model_name="airuntimesettings",
            name="google_service_account_json",
            field=apps.ai_config.models.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name="airuntimesettings",
            name="google_slot_minutes",
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
