# Generated by Django 5.2.12 on 2026-04-05 17:55

import apps.whatsapp.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppBusinessAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120)),
                ('waba_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('access_token', apps.whatsapp.models.EncryptedTextField()),
                ('api_version', models.CharField(default='v21.0', max_length=12)),
                ('webhook_verify_token', models.CharField(max_length=255)),
                ('webhook_secret', apps.whatsapp.models.EncryptedTextField(blank=True)),
            ],
            options={
                'verbose_name': 'WhatsApp business account',
                'verbose_name_plural': 'WhatsApp business accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppPhoneNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone_number_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('display_phone_number', models.CharField(max_length=40)),
                ('verified_name', models.CharField(blank=True, max_length=255)),
                ('quality_rating', models.CharField(default='UNKNOWN', max_length=30)),
                ('messaging_limit', models.CharField(default='TIER_250', max_length=30)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('banned', 'Banned'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='whatsapp.whatsappbusinessaccount')),
            ],
            options={
                'verbose_name': 'WhatsApp phone number',
                'verbose_name_plural': 'WhatsApp phone numbers',
                'ordering': ['display_phone_number'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_template_id', models.CharField(blank=True, max_length=128)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(choices=[('marketing', 'Marketing'), ('utility', 'Utility'), ('authentication', 'Authentication')], max_length=20)),
                ('language', models.CharField(default='es', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paused', 'Paused'), ('disabled', 'Disabled')], db_index=True, default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('header_type', models.CharField(choices=[('none', 'None'), ('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='none', max_length=20)),
                ('header_content', models.TextField(blank=True)),
                ('body_text', models.TextField()),
                ('footer_text', models.CharField(blank=True, max_length=255)),
                ('buttons', models.JSONField(blank=True, default=list)),
                ('example_values', models.JSONField(blank=True, default=list)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='whatsapp.whatsappbusinessaccount')),
            ],
            options={
                'verbose_name': 'WhatsApp template',
                'verbose_name_plural': 'WhatsApp templates',
                'ordering': ['name'],
                'unique_together': {('account', 'name', 'language')},
            },
        ),
    ]
