# Generated by Django 5.2.6 on 2026-05-11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0006_conversation_deal_and_unique_by_deal"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarBookingDraft",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_selection", "Pending selection"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending_selection",
                        max_length=24,
                    ),
                ),
                ("offered_slots", models.JSONField(blank=True, default=list)),
                ("timezone", models.CharField(default="America/Bogota", max_length=64)),
                ("selected_slot", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.PositiveSmallIntegerField(default=30)),
                ("google_event_id", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "conversation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_booking_draft",
                        to="chat.conversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar booking draft",
                "verbose_name_plural": "Calendar booking drafts",
                "ordering": ["-updated_at"],
            },
        ),
    ]
