# Generated by Django 5.2.12 on 2026-04-01 16:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contract_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('contract_type', models.CharField(choices=[('service', 'Service'), ('product', 'Product'), ('subscription', 'Subscription'), ('consulting', 'Consulting'), ('other', 'Other')], default='service', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_signature', 'Pending signature'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('signing_date', models.DateField(blank=True, null=True)),
                ('payment_terms', models.CharField(choices=[('upfront', 'Upfront'), ('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_60', 'Net 60'), ('installments', 'Installments'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('payment_schedule', models.JSONField(blank=True, default=list)),
                ('auto_renewal', models.BooleanField(default=False)),
                ('renewal_period_days', models.IntegerField(blank=True, null=True)),
                ('cancellation_notice_days', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='finance/contracts/%Y/%m/')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_contracts_assigned', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_contracts', to='crm.company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_contracts', to='crm.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_contracts_created', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_contracts', to='crm.deal')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='finance/contract-documents/%Y/%m/')),
                ('document_type', models.CharField(choices=[('contract', 'Contract'), ('amendment', 'Amendment'), ('annex', 'Annex'), ('addendum', 'Addendum'), ('other', 'Other')], default='other', max_length=20)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='finance.contract')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_contract_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract document',
                'verbose_name_plural': 'Contract documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('partially_paid', 'Partially paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('void', 'Void')], db_index=True, default='draft', max_length=20)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_invoices_assigned', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='crm.company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='crm.contact')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='finance.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_invoices_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.invoice')),
            ],
            options={
                'verbose_name': 'Invoice item',
                'verbose_name_plural': 'Invoice items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('cash', 'Cash'), ('credit_card', 'Credit card'), ('check', 'Check'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='finance/payments/%Y/%m/')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.invoice')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
