# Generated by Django 5.2.6 on 2026-05-12 12:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0004_document_ai_configuration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkedInWebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("event_name", models.CharField(db_index=True, max_length=64)),
                ("external_event_id", models.CharField(max_length=255, unique=True)),
                ("account_external_id", models.CharField(blank=True, max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(db_index=True, default="received", max_length=32),
                ),
            ],
            options={
                "verbose_name": "LinkedIn Webhook Event",
                "verbose_name_plural": "LinkedIn Webhook Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LinkedInAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("unipile_account_id", models.CharField(max_length=128, unique=True)),
                ("linkedin_user_id", models.CharField(blank=True, max_length=255)),
                ("linkedin_name", models.CharField(blank=True, max_length=255)),
                ("linkedin_profile_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activa"),
                            ("reconnecting", "Reconectando"),
                            ("disconnected", "Desconectada"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="disconnected",
                        max_length=32,
                    ),
                ),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linkedin_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "LinkedIn Account",
                "verbose_name_plural": "LinkedIn Accounts",
            },
        ),
        migrations.CreateModel(
            name="LinkedInProspect",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("linkedin_profile_id", models.CharField(max_length=255)),
                ("linkedin_profile_url", models.URLField(blank=True)),
                ("full_name", models.CharField(max_length=255)),
                ("headline", models.CharField(blank=True, max_length=255)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("job_title", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("profile_picture_url", models.URLField(blank=True)),
                (
                    "network_distance",
                    models.CharField(
                        choices=[
                            ("first", "1er grado"),
                            ("second", "2do grado"),
                            ("third", "3er grado"),
                            ("out_of_network", "Fuera de red"),
                        ],
                        default="out_of_network",
                        max_length=32,
                    ),
                ),
                (
                    "funnel_stage",
                    models.CharField(
                        choices=[
                            ("prospect_identified", "Prospecto identificado"),
                            ("invitation_sent", "Invitación enviada"),
                            ("connection_accepted", "Conexión aceptada"),
                            ("first_message_sent", "Primer contacto enviado"),
                            ("in_conversation", "En conversación"),
                            ("meeting_scheduled", "Reunión agendada"),
                            ("proposal_sent", "Propuesta enviada"),
                            ("client", "Cliente"),
                            ("discarded", "Descartado"),
                        ],
                        db_index=True,
                        default="prospect_identified",
                        max_length=64,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("unipile_chat_id", models.CharField(blank=True, max_length=255)),
                ("invitation_sent_at", models.DateTimeField(blank=True, null=True)),
                ("invitation_accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invitation_status",
                    models.CharField(
                        choices=[
                            ("not_sent", "No enviada"),
                            ("pending", "Pendiente"),
                            ("accepted", "Aceptada"),
                            ("declined", "Rechazada"),
                            ("withdrawn", "Retirada"),
                        ],
                        db_index=True,
                        default="not_sent",
                        max_length=32,
                    ),
                ),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_message_direction",
                    models.CharField(
                        blank=True,
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=16,
                    ),
                ),
                ("is_discarded", models.BooleanField(db_index=True, default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prospects",
                        to="linkedin.linkedinaccount",
                    ),
                ),
                (
                    "crm_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linkedin_prospects",
                        to="crm.contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "LinkedIn Prospect",
                "verbose_name_plural": "LinkedIn Prospects",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ProspectStageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "from_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("prospect_identified", "Prospecto identificado"),
                            ("invitation_sent", "Invitación enviada"),
                            ("connection_accepted", "Conexión aceptada"),
                            ("first_message_sent", "Primer contacto enviado"),
                            ("in_conversation", "En conversación"),
                            ("meeting_scheduled", "Reunión agendada"),
                            ("proposal_sent", "Propuesta enviada"),
                            ("client", "Cliente"),
                            ("discarded", "Descartado"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "to_stage",
                    models.CharField(
                        choices=[
                            ("prospect_identified", "Prospecto identificado"),
                            ("invitation_sent", "Invitación enviada"),
                            ("connection_accepted", "Conexión aceptada"),
                            ("first_message_sent", "Primer contacto enviado"),
                            ("in_conversation", "En conversación"),
                            ("meeting_scheduled", "Reunión agendada"),
                            ("proposal_sent", "Propuesta enviada"),
                            ("client", "Cliente"),
                            ("discarded", "Descartado"),
                        ],
                        max_length=64,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linkedin_stage_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prospect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_logs",
                        to="linkedin.linkedinprospect",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prospect Stage Log",
                "verbose_name_plural": "Prospect Stage Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                ("keywords", models.CharField(max_length=255)),
                ("job_title", models.CharField(blank=True, max_length=255)),
                ("industry", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "network_distance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("first", "1er grado"),
                            ("second", "2do grado"),
                            ("third", "3er grado"),
                            ("out_of_network", "Fuera de red"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Diaria"),
                            ("every_2_days", "Cada 2 días"),
                            ("weekly", "Semanal"),
                        ],
                        default="daily",
                        max_length=32,
                    ),
                ),
                ("last_executed_at", models.DateTimeField(blank=True, null=True)),
                ("total_results_found", models.PositiveIntegerField(default=0)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to="linkedin.linkedinaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Search",
                "verbose_name_plural": "Saved Searches",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="linkedinprospect",
            name="saved_search",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prospects",
                to="linkedin.savedsearch",
            ),
        ),
        migrations.CreateModel(
            name="InvitationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=120)),
                ("body", models.CharField(max_length=300)),
                ("times_used", models.PositiveIntegerField(default=0)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation_templates",
                        to="linkedin.linkedinaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitation Template",
                "verbose_name_plural": "Invitation Templates",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "name"),
                        name="linkedin_unique_invitation_template_name",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=120)),
                ("body", models.TextField()),
                ("times_used", models.PositiveIntegerField(default=0)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_templates",
                        to="linkedin.linkedinaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Template",
                "verbose_name_plural": "Message Templates",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "name"),
                        name="linkedin_unique_message_template_name",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="linkedinprospect",
            index=models.Index(
                fields=["funnel_stage", "invitation_status"],
                name="linkedin_li_funnel__4359c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="linkedinprospect",
            index=models.Index(
                fields=["last_message_at"], name="linkedin_li_last_me_7691d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="linkedinprospect",
            index=models.Index(
                fields=["is_discarded"], name="linkedin_li_is_disc_a36993_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="linkedinprospect",
            index=models.Index(
                fields=["account", "saved_search"],
                name="linkedin_li_account_318a62_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="linkedinprospect",
            index=models.Index(
                fields=["linkedin_profile_id"], name="linkedin_li_linkedi_227806_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="linkedinprospect",
            constraint=models.UniqueConstraint(
                fields=("account", "linkedin_profile_id"),
                name="linkedin_unique_prospect_by_account_profile",
            ),
        ),
    ]
