# Generated by Django 5.2.6 on 2026-06-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linkedin", "0002_prospect_pipeline_fields_and_stage_remap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prospectstagelog",
            name="from_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("contacted", "Contactado"),
                    ("low_interest", "Interés bajo"),
                    ("high_interest", "Interés alto"),
                    ("meeting_scheduling", "En agendamiento de reunión"),
                    ("proposal_sent", "Propuesta enviada"),
                    ("no_response", "No contesta"),
                    ("discarded", "Descartado"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="prospectstagelog",
            name="to_stage",
            field=models.CharField(
                choices=[
                    ("contacted", "Contactado"),
                    ("low_interest", "Interés bajo"),
                    ("high_interest", "Interés alto"),
                    ("meeting_scheduling", "En agendamiento de reunión"),
                    ("proposal_sent", "Propuesta enviada"),
                    ("no_response", "No contesta"),
                    ("discarded", "Descartado"),
                ],
                max_length=64,
            ),
        ),
    ]
