# Generated by Django 5.2.6 on 2026-04-05 18:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
        ("whatsapp", "0002_whatsappphonenumber_default_assigned_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineAutomationConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("auto_move_on_first_response", models.BooleanField(default=True)),
                ("auto_move_on_meeting", models.BooleanField(default=True)),
                ("auto_move_on_proposal", models.BooleanField(default=True)),
                ("auto_move_on_contract", models.BooleanField(default=True)),
                ("auto_move_on_contract_signed", models.BooleanField(default=True)),
                ("stale_deal_days", models.PositiveIntegerField(default=14)),
                ("auto_close_lost_days", models.PositiveIntegerField(default=45)),
                ("notify_on_stage_change", models.BooleanField(default=True)),
                ("log_auto_movements", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Pipeline automation configuration",
                "verbose_name_plural": "Pipeline automation configurations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="deal",
            name="is_stale",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="deal",
            name="source",
            field=models.CharField(
                choices=[
                    ("whatsapp", "WhatsApp"),
                    ("manual", "Manual"),
                    ("website", "Website"),
                    ("referral", "Referral"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("call", "Call"),
                    ("email", "Email"),
                    ("meeting", "Meeting"),
                    ("follow_up", "Follow up"),
                    ("note", "Note"),
                    ("task", "Task"),
                    ("whatsapp", "WhatsApp"),
                ],
                default="note",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="source",
            field=models.CharField(
                choices=[
                    ("whatsapp", "WhatsApp"),
                    ("manual", "Manual"),
                    ("website", "Website"),
                    ("referral", "Referral"),
                    ("social_media", "Social media"),
                    ("cold_call", "Cold call"),
                    ("event", "Event"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="stage",
            field=models.CharField(
                choices=[
                    ("new_lead", "New lead"),
                    ("contacted", "Contacted"),
                    ("qualified", "Qualified"),
                    ("qualification", "Qualification"),
                    ("proposal", "Proposal"),
                    ("negotiation", "Negotiation"),
                    ("closed_won", "Closed won"),
                    ("closed_lost", "Closed lost"),
                ],
                db_index=True,
                default="qualification",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LeadEngineConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("auto_create_contact", models.BooleanField(default=True)),
                ("auto_create_deal", models.BooleanField(default=True)),
                (
                    "default_deal_pipeline_stage",
                    models.CharField(default="new_lead", max_length=20),
                ),
                (
                    "default_deal_title_template",
                    models.CharField(
                        default="Lead WhatsApp - {contact_name}", max_length=255
                    ),
                ),
                ("auto_create_follow_up", models.BooleanField(default=True)),
                ("max_response_time_minutes", models.PositiveIntegerField(default=60)),
                (
                    "auto_complete_activities_on_reply",
                    models.BooleanField(default=True),
                ),
                (
                    "default_intent_level",
                    models.CharField(
                        choices=[
                            ("cold", "Cold"),
                            ("warm", "Warm"),
                            ("hot", "Hot"),
                            ("very_hot", "Very hot"),
                        ],
                        default="warm",
                        max_length=20,
                    ),
                ),
                (
                    "default_lifecycle_stage",
                    models.CharField(
                        choices=[
                            ("new_lead", "New lead"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("proposal", "Proposal"),
                            ("negotiation", "Negotiation"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        default="new_lead",
                        max_length=20,
                    ),
                ),
                (
                    "assignment_strategy",
                    models.CharField(
                        choices=[
                            ("round_robin", "Round robin"),
                            ("least_busy", "Least busy"),
                            ("specific_user", "Specific user"),
                            ("by_phone_number", "By phone number"),
                        ],
                        default="round_robin",
                        max_length=20,
                    ),
                ),
                ("notify_on_new_lead", models.BooleanField(default=True)),
                ("notify_on_returning_contact", models.BooleanField(default=False)),
                (
                    "assignment_specific_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_lead_engine_specific_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignment_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="crm_lead_engine_assignment_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "auto_response_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_engine_auto_response_configs",
                        to="whatsapp.whatsapptemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead engine configuration",
                "verbose_name_plural": "Lead engine configurations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DealStageHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("from_stage", models.CharField(blank=True, max_length=20)),
                ("to_stage", models.CharField(max_length=20)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("first_response", "First response"),
                            ("meeting_scheduled", "Meeting scheduled"),
                            ("proposal_sent", "Proposal sent"),
                            ("contract_created", "Contract created"),
                            ("contract_signed", "Contract signed"),
                            ("stale_timeout", "Stale timeout"),
                            ("lead_created", "Lead created"),
                        ],
                        db_index=True,
                        default="manual",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_history",
                        to="crm.deal",
                    ),
                ),
                (
                    "moved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_deal_stage_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Deal stage history",
                "verbose_name_plural": "Deal stage histories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["deal", "created_at"],
                        name="crm_dealsta_deal_id_9177c5_idx",
                    ),
                    models.Index(
                        fields=["trigger", "created_at"],
                        name="crm_dealsta_trigger_c3c8f5_idx",
                    ),
                ],
            },
        ),
    ]
