# Generated by Django 5.2.6 on 2026-04-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_config", "0005_aiconfiguration_profile_fields_and_global_ai_mode"),
        ("crm", "0003_document_is_global_knowledge"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="ai_configuration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="knowledge_documents",
                to="ai_config.aiconfiguration",
            ),
        ),
    ]
