# Generated by Django 5.2.6 on 2026-08-05 22:21

import uuid
from django.db import migrations, models


def seed_pipeline_stages(apps, schema_editor):
    PipelineStage = apps.get_model("crm", "PipelineStage")
    stage_defaults = [
        {
            "key": "new_lead",
            "name": "Nuevo lead",
            "position": 10,
            "accent_color": "#3b82f6",
            "tint_color": "rgba(59, 130, 246, 0.14)",
        },
        {
            "key": "contacted",
            "name": "Contactado",
            "position": 20,
            "accent_color": "#0ea5e9",
            "tint_color": "rgba(14, 165, 233, 0.14)",
        },
        {
            "key": "qualified",
            "name": "Calificado",
            "position": 30,
            "accent_color": "#8b5cf6",
            "tint_color": "rgba(139, 92, 246, 0.14)",
        },
        {
            "key": "proposal",
            "name": "Propuesta",
            "position": 40,
            "accent_color": "#f59e0b",
            "tint_color": "rgba(245, 158, 11, 0.16)",
        },
        {
            "key": "negotiation",
            "name": "Negociación",
            "position": 50,
            "accent_color": "#f97316",
            "tint_color": "rgba(249, 115, 22, 0.16)",
        },
        {
            "key": "realizar_llamada",
            "name": "Realizar llamada",
            "position": 60,
            "accent_color": "#ef4444",
            "tint_color": "rgba(239, 68, 68, 0.14)",
        },
        {
            "key": "closed_won",
            "name": "Cerrado ganado",
            "position": 70,
            "accent_color": "#16a34a",
            "tint_color": "rgba(22, 163, 74, 0.16)",
            "is_closed_stage": True,
            "is_won_stage": True,
        },
        {
            "key": "closed_lost",
            "name": "Cerrado perdido",
            "position": 80,
            "accent_color": "#64748b",
            "tint_color": "rgba(100, 116, 139, 0.16)",
            "is_closed_stage": True,
            "is_lost_stage": True,
        },
    ]
    for item in stage_defaults:
        PipelineStage.objects.update_or_create(
            key=item["key"],
            defaults=item,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_document_ai_configuration"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("key", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                ("position", models.PositiveIntegerField(db_index=True, default=0)),
                ("accent_color", models.CharField(default="#3b82f6", max_length=20)),
                (
                    "tint_color",
                    models.CharField(default="rgba(59, 130, 246, 0.14)", max_length=40),
                ),
                ("is_closed_stage", models.BooleanField(db_index=True, default=False)),
                ("is_won_stage", models.BooleanField(db_index=True, default=False)),
                ("is_lost_stage", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "verbose_name": "Pipeline stage",
                "verbose_name_plural": "Pipeline stages",
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="deal",
            name="business_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pipelineautomationconfig",
            name="closed_chat_stage_key",
            field=models.CharField(default="realizar_llamada", max_length=50),
        ),
        migrations.AlterField(
            model_name="deal",
            name="stage",
            field=models.CharField(db_index=True, default="qualified", max_length=50),
        ),
        migrations.AlterField(
            model_name="dealstagehistory",
            name="from_stage",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="dealstagehistory",
            name="to_stage",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="dealstagehistory",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("first_response", "First response"),
                    ("meeting_scheduled", "Meeting scheduled"),
                    ("proposal_sent", "Proposal sent"),
                    ("contract_created", "Contract created"),
                    ("contract_signed", "Contract signed"),
                    ("stale_timeout", "Stale timeout"),
                    ("lead_created", "Lead created"),
                    ("chat_window_closed", "Chat window closed"),
                    ("chat_closed_manual", "Chat closed manually"),
                    ("business_summary_refresh", "Business summary refresh"),
                ],
                db_index=True,
                default="manual",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="leadengineconfig",
            name="default_deal_pipeline_stage",
            field=models.CharField(default="new_lead", max_length=50),
        ),
        migrations.RunPython(seed_pipeline_stages, migrations.RunPython.noop),
    ]
