# Generated by Django 5.2.6 on 2026-08-05 21:40

import uuid
from django.db import migrations, models


def seed_default_pipeline_stages(apps, schema_editor):
    PipelineStage = apps.get_model("crm", "PipelineStage")
    defaults = [
        ("new_lead", "Nuevo lead", "#3b82f6", "rgba(59, 130, 246, 0.14)", False, False, False),
        ("contacted", "Contactado", "#0ea5e9", "rgba(14, 165, 233, 0.14)", False, False, False),
        ("realizar_llamada", "Realizar llamada", "#f59e0b", "rgba(245, 158, 11, 0.14)", False, False, False),
        ("qualified", "Calificado", "#8b5cf6", "rgba(139, 92, 246, 0.14)", False, False, False),
        ("qualification", "Calificación (legacy)", "#64748b", "rgba(100, 116, 139, 0.14)", False, False, False),
        ("proposal", "Propuesta", "#f97316", "rgba(249, 115, 22, 0.14)", False, False, False),
        ("negotiation", "Negociación", "#ef4444", "rgba(239, 68, 68, 0.14)", False, False, False),
        ("closed_won", "Ganado", "#22c55e", "rgba(34, 197, 94, 0.14)", True, True, False),
        ("closed_lost", "Perdido", "#94a3b8", "rgba(148, 163, 184, 0.18)", True, False, True),
    ]
    for position, (key, name, accent, tint, is_closed, is_won, is_lost) in enumerate(defaults):
        PipelineStage.objects.update_or_create(
            key=key,
            defaults={
                "name": name,
                "position": position,
                "accent_color": accent,
                "tint_color": tint,
                "is_closed_stage": is_closed,
                "is_won_stage": is_won,
                "is_lost_stage": is_lost,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_document_ai_configuration"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("key", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                ("position", models.PositiveIntegerField(db_index=True, default=0)),
                ("accent_color", models.CharField(default="#3b82f6", max_length=20)),
                (
                    "tint_color",
                    models.CharField(default="rgba(59, 130, 246, 0.14)", max_length=40),
                ),
                ("is_closed_stage", models.BooleanField(db_index=True, default=False)),
                ("is_won_stage", models.BooleanField(db_index=True, default=False)),
                ("is_lost_stage", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "verbose_name": "Pipeline stage",
                "verbose_name_plural": "Pipeline stages",
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="deal",
            name="business_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pipelineautomationconfig",
            name="closed_chat_stage_key",
            field=models.CharField(default="realizar_llamada", max_length=50),
        ),
        migrations.AlterField(
            model_name="deal",
            name="stage",
            field=models.CharField(db_index=True, default="qualified", max_length=50),
        ),
        migrations.AlterField(
            model_name="dealstagehistory",
            name="from_stage",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="dealstagehistory",
            name="to_stage",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="dealstagehistory",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("first_response", "First response"),
                    ("meeting_scheduled", "Meeting scheduled"),
                    ("proposal_sent", "Proposal sent"),
                    ("contract_created", "Contract created"),
                    ("contract_signed", "Contract signed"),
                    ("stale_timeout", "Stale timeout"),
                    ("lead_created", "Lead created"),
                    ("chat_window_closed", "Chat window closed"),
                    ("chat_closed_manual", "Chat closed manually"),
                    ("business_summary_refresh", "Business summary refresh"),
                ],
                db_index=True,
                default="manual",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="leadengineconfig",
            name="default_deal_pipeline_stage",
            field=models.CharField(default="new_lead", max_length=50),
        ),
        migrations.RunPython(seed_default_pipeline_stages, migrations.RunPython.noop),
    ]
