# Generated by Django 5.2.6 on 2026-08-06 18:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_fix_realizar_llamada_closed_stage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DealCall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField()),
                (
                    "called_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_deal_calls_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls",
                        to="crm.deal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deal call",
                "verbose_name_plural": "Deal calls",
                "ordering": ["-called_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["deal", "called_at"],
                        name="crm_dealcal_deal_id_f35632_idx",
                    ),
                    models.Index(
                        fields=["called_at"], name="crm_dealcal_called__d9ff1d_idx"
                    ),
                ],
            },
        ),
    ]
