# Generated by Django 5.2.6 on 2026-03-31 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_config", "0003_rag_and_ai_rag_fields"),
        ("chat", "0002_bc_safety_handoff"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="ai_configuration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="ai_config.aiconfiguration",
            ),
        ),
    ]
