# Generated by Django 5.2.6 on 2026-04-05 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_conversation_customer_service_window_expires_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                condition=models.Q(("whatsapp_message_id", ""), _negated=True),
                fields=("whatsapp_message_id",),
                name="chat_unique_non_empty_whatsapp_message_id",
            ),
        ),
    ]
