# Generated by Django 5.2.6 on 2026-05-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_conversation_deal_and_unique_by_deal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="channel",
            field=models.CharField(
                choices=[
                    ("whatsapp", "WhatsApp"),
                    ("internal", "Internal"),
                    ("linkedin", "LinkedIn"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
