# Generated by Django 5.2.6 on 2026-08-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_alter_conversation_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
