# Generated by Django 5.2.6 on 2026-03-31 18:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("chunk_index", models.PositiveIntegerField(db_index=True)),
                ("text", models.TextField()),
                ("embedding", models.JSONField(default=list)),
                (
                    "embedding_model",
                    models.CharField(default="text-embedding-3-small", max_length=80),
                ),
                ("token_count", models.PositiveIntegerField(default=0)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rag_chunks",
                        to="crm.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document chunk",
                "verbose_name_plural": "Document chunks",
                "ordering": ["document_id", "chunk_index"],
                "indexes": [
                    models.Index(
                        fields=["document", "chunk_index"],
                        name="rag_documen_documen_637082_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "chunk_index"),
                        name="rag_unique_document_chunk_index",
                    )
                ],
            },
        ),
    ]
